###登录 login
POST {{host}}/user/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data); %}


###菜单列表 menu_list
POST {{host}}/menu/queryMenuList
Content-Type: application/json
Authorization: Bearer {{token}}

###新增菜单 menu_save
POST {{host}}/menu/saveMenu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "menuName": "测试123123",
  "menuType": 2,
  "statusId": 1,
  "sort": 1,
  "parentId": 0,
  "menuUrl": "/abc12",
  "apiUrl": "",
  "menuIcon": "Setting",
  "remark": ""
}

###删除菜单 menu_delete
POST {{host}}/menu/deleteMenu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [102]
}
###更新菜单 menu_update
POST {{host}}/menu/updateMenu
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 102,
  "menuName": "测试kk",
  "menuType": 2,
  "statusId": 1,
  "sort": 1,
  "parentId": 0,
  "menuUrl": "/abc",
  "apiUrl": "",
  "menuIcon": "Setting",
  "remark": ""
}


