###登录 login
POST {{host}}/user/login
Content-Type: application/json

{
  "mobile": "18613030352",
  "password": "123456"
}
> {% client.global.set("token", response.body.data); %}

###查询角色菜单 query_role_menu
GET {{host}}/role/queryRoleMenuList?roleId=3
Content-Type: application/json
Authorization: Bearer {{token}}


###更新角色菜单 update_role_menu
POST {{host}}/role/updateRoleMenuList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roleId": 3,
  "menuIds": [1,2,3,8]
}
###角色列表 role_list
POST {{host}}/role/queryRoleList
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pageNo": 1,
  "pageSize": 10
}
###新增角色 role_save
POST {{host}}/role/saveRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "roleName": "test1",
  "statusId": 1,
  "sort": 1,
  "remark": "1"
}
###删除角色 role_delete
DELETE {{host}}/role/deleteRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "ids": [8]
}
###更新角色 role_update
POST {{host}}/role/updateRole
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "id": 8,
  "roleName": "testsfsf",
  "statusId": 1,
  "sort": 1,
  "remark": "tst"
}
